# V3 MongoDB connection string
name: Build and deploy Node.js app to Azure Web App - Needle # V3 MongoDB connection string test

on:
  push:
    branches:
      - New-JS-Files
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd Needle11 # Ensure the directory is correct
          npm install mongodb
          npm install mongoose@latest
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip Needle11/public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID}}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Configure Azure Web App to serve static files and set environment variables
        run: |
          az webapp config set \
            --name 'Needle' \
            --resource-group 'Needle' \
            --linux-fx-version "NODE|22-lts" \
            --startup-file "npx serve Needle11/public"
          az webapp config appsettings set \
            --name 'Needle' \
            --resource-group 'Needle' \
            --settings MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Needle'
          slot-name: 'Production'
          package: release.zip
